//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorguEkran
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHesap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblHesap()
        {
            this.TblOdeme = new HashSet<TblOdeme>();
            this.TblOdeme1 = new HashSet<TblOdeme>();
        }
    
        public string Iban { get; set; }
        public Nullable<decimal> Alacaklı_Tutar { get; set; }
        public Nullable<decimal> Borçlu_Tutar { get; set; }
        public string Döviz_Kodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOdeme> TblOdeme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOdeme> TblOdeme1 { get; set; }
    }
}
