//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorguEkran
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOdeme
    {
        public int ID { get; set; }
        public string TCKN { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<System.DateTime> Başlangıç_Tarihi { get; set; }
        public Nullable<System.DateTime> Bitiş_Tarihi { get; set; }
        public string Döviz_Kodu { get; set; }
        public Nullable<System.DateTime> Ödeme_Tarihi { get; set; }
        public string Durum_Kodu { get; set; }
        public string Alacaklı_Iban { get; set; }
        public string Borçlu_İban { get; set; }
        public string Açıklama { get; set; }
    
        public virtual TblHesap TblHesap { get; set; }
        public virtual TblHesap TblHesap1 { get; set; }
    }
}
